name: gazelle_client
description: An easy to use client to connect to Gazelle.
version: 0.2.0
repository: https://github.com/intales/gazelle/tree/main/packages/gazelle_client

environment:
  sdk: ^3.4.3

dependencies:
  gazelle_serialization: ^0.1.1
  http: ^1.2.1

dev_dependencies:
  gazelle_core: ^0.5.0
  lints: ^3.0.0
  test: ^1.24.0
