name: gazelle_jwt
description: Plugin for JSON Web Token (JWT) authentication in Gazelle, providing functionality to sign, verify, and handle JWT tokens during HTTP request processing.
version: 0.7.0
repository: https://github.com/intales/gazelle/tree/main/packages/gazelle_jwt

environment:
  sdk: ^3.3.2

dependencies:
  dart_jsonwebtoken: ^2.13.0
  gazelle_core: ^0.8.0

dev_dependencies:
  http: ^1.2.1
  lints: ">=3.0.0 <6.0.0"
  test: ^1.24.0
