name: gazelle_benchmark
description: Benchmark tool for the Gazelle backend framework.
version: 0.1.0
repository: https://github.com/intales/gazelle/packages/gazelle_benchmark
publish_to: none

environment:
  sdk: ^3.3.2

dev_dependencies:
  http: ^1.2.1
  lints: ^5.0.0
  test: ^1.24.0
dependencies:
  gazelle_core: ^0.8.0
