name: gazelle_logger
description: Provides logging functionality for Gazelle applications, allowing developers to log incoming requests and outgoing responses.
version: 0.6.0+2
repository: https://github.com/intales/gazelle/tree/main/packages/gazelle_logger

environment:
  sdk: ^3.3.3

dev_dependencies:
  http: ^1.2.1
  lints: ">=3.0.0 <6.0.0"
  test: ^1.24.0
dependencies:
  gazelle_core: ^0.8.0
  logger: ^2.2.0
