name: gazelle_cors
description: Gazelle CORS Plugin is a Dart package that provides Cross-Origin Resource Sharing (CORS) support for Gazelle applications.
version: 0.6.0+2
repository: https://github.com/intales/gazelle/tree/main/packages/gazelle_cors

environment:
  sdk: ^3.3.2

dev_dependencies:
  http: ^1.2.1
  lints: ">=3.0.0 <6.0.0"
  test: ^1.24.0
dependencies:
  gazelle_core: ^0.8.0
