name: gazelle_cli
description: A CLI tool to manage applications built with Gazelle framework.
version: 0.1.0
repository: https://github.com/intales/gazelle/tree/main/packages/gazelle_cli

environment:
  sdk: ^3.3.3

executables:
  gazelle: gazelle_cli

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
dependencies:
  args: ^2.5.0
  cli_spin: ^1.0.1
  yaml: ^3.1.2
